### PR TITLE
#167730744 Implements Reset password feature

### PR DESCRIPTION
**Pull request by conquext**
#### What does this PR do?
* Resets user password by sending a cryptographically stamped token to the email of a registered user on request. The token allows a user to set new password. Only a valid user can reset passwords, invalid requests are sent links to sign up on the website
#### Description of Task to be completed?
* Sequelize Models for Login, and Reset table and relations
* Seed users data to test functionality
* Unit test to verify proper validations and error handling
* Email provider to handle secured delivery of reset links
#### How should this be manually tested?
* git clone this branch `ft-reset-password-167730740`
* cd to the project
* run `npm install`
* instantiate sequelize for Login and Rest models
* Sync database with raw data
* run npm start:dev
* set PORT on .env to 4000
 * set LOCALHOST on .env to localhost:4000
* set TOKENEXPIRY to any integer value
* EMAIL to an gmail address your control
* CLIENT_URL link to an heroku url where the api is served or any local server
> Provide the following gmail credentials to authenticate 02AUTH
>* GMAIL_ID
>* GMAIL_SECRET 
>* GMAIL_REFRESH 
* go to localhost:4000/forgetpassword and supply a one of the emails you sync with
* try invalid data to catch errors

#### Any background context you want to provide?
* Users may be lose access to their account, but are able to retrieve it with their email. Emails provide proof of authentication and obfuscate the membership of the network to only the members.

* Tests are not currently passing but the implementation exposes several keys validation components and file structure that are important to be maintained for the project development.

*Blockers include incomplete database configuration, but the api are well exposed and presents opportunity for the database migrations to be well tested and reviewed.

#### What are the relevant pivotal tracker stories?
* [#167730744](https://www.pivotaltracker.com/n/projects/2382004/stories/167730744)

#### Screenshots or gifs (if appropriate)
* 
image

#### Questions:
* N/A

### CODE REVIEW

**Comment by OlawaleJoseph** [comment]
Thumbs Up, Rasheed. I noted the following in your work:
  1. In the routes/api/users.js file, you used mongoose. Shouldn't it be Sequelize or dummy data?
  2. In the sendMail file, you initialized dotenv. That is necessary as it has been initialized in the project's index file.
  3. An example of the environmental variables needed should be in the .env.example file

**Comment by wahabtobibello** [comment]
@conquext 

> instantiate sequelize for Login and Rest models

I don't quite get this step

I ran `npm run start:dev` after `npm install` and I got ...
Screen Shot 2019-08-21 at 9 25 40 AM

What am I doing wrong?

**Comment by conquext** [comment]
> @conquext
> 
> > instantiate sequelize for Login and Rest models
> 
> I don't quite get this step
> 
> I ran `npm run start:dev` after `npm install` and I got ...
> Screen Shot 2019-08-21 at 9 25 40 AM
> 
> What am I doing wrong?

My bad @wahaaabello . I cannot make email a foreign key without applying a unique constraint. Weird that i didn't get this error on my system.

**Comment by ola357** [comment]
error2

I keep getting this after running `npm install`

**Comment by conquext** [comment]
> error2
> 
> I keep getting this after running `npm install`

True, crypto is now a package in nodejs. Thanks, I  have removed it from package.json.

**Comment by wahabtobibello** [comment]
Screen Shot 2019-08-21 at 10 46 14 AM

@conquext I'm still getting this error

**Comment by ola357** [comment]
error3

This is the error I get
I think the sequelize PR has been merged, you can work with that 2

**Comment by wahabtobibello** [comment]
@conquext Merge `stage`

**Pull request closed without merging**
