### PR TITLE
#167730737 configure heroku for the project

### PR DESCRIPTION
**Pull request by Dolapo47**
#### What does this PR do?
* Configure heroku to enable project to be deployed and individual PR reviewed
#### Description of Task to be completed?
* create an account on heroku
* create an app that houses the project
* create pipeline for the app
* create a app.json file that enables review of each PR
* add heroku-postgres as an addon
#### How should this be manually tested?
* Team member creates a PR on github
* PR can be reviewed on heroku
#### Any background context you want to provide?
* N/A
#### What are the relevant pivotal tracker stories?
* [PT story ID](https://www.pivotaltracker.com/story/show/167730737)
#### Screenshots or gifs (if appropriate)
Screenshot (7)
#### Questions:
* N/A

### CODE REVIEW

**Review by zanio — COMMENTED** [review]
Great Job @Dolapo47 , the heroku link is live on my branch! Does this means that every branch pushed to github automatically get deployed on heroku and i can do any route check as i would have done with my local environment ?

**Review by conquext — APPROVED** [review]
Great job, ok to merge.

**Comment by Dolapo47** [comment]
> Great Job @Dolapo47 , the heroku link is live on my branch! Does this means that every branch pushed to github automatically get deployed on heroku and i can do any route check as i would have done with my local environment ?

once a pr is raised, it gets deployed on heroku for review,if all is fine it is moved to the staging pipeline on heroku

**Review by zanio — APPROVED** [review]
Great. Ready to merge.

**Review by marusoft — APPROVED** [review]
awesome job @Dolapo47

**Pull request merged**
