### PR TITLE
#167730735 setup api documentation using swagger

### PR DESCRIPTION
**Pull request by marusoft**
#### What does this PR do?
* Setup API documentation using swagger
#### Description of Task to be completed?
* Research on & choose a CSS framework, and a suitable tool for building all your mockups.
#### How should this be manually tested?
* git clone this branch [setup API Documentation using swagger](https://github.com/andela/firestar-backend/tree/ch-setup-api-documentation-using-swagger-%23167730735)
* cd `firestar-backend`
* Checkout to the branch `ch-setup-api-documentation-using-swagger-#167730735`
* run `npm run start:dev`
* open browser of choice.
* And visit  [firestar-backend API Documentation](http://localhost:3000/api-docs)

#### Any background context you want to provide?
* N/A
#### What are the relevant pivotal tracker stories?
* [#167730735](ch-setup-api-documentation-using-swagger-#167730735)
#### Questions:
* N/A

### CODE REVIEW

**Review by dewaleolaoye — CHANGES_REQUESTED** [review]
Well done, please include the project description

**Comment by marusoft** [comment]
thanks, will get it fix

**Review by ola357 — APPROVED** [review]
Nice work @marusoft . As the project develops, we will remove the default api endpoints

**Review by dewaleolaoye — APPROVED** [review]
Well done

**Comment by marusoft** [comment]
thanks guys

**Comment by rovilay** [comment]
@marusoft Please update the PR title to conform with the standard.

**Comment by rovilay** [comment]
@marusoft Good work so far. Please remove the `mongodb` config in the `index` file so as to prevent errors when trying to run the app.

**Comment by rovilay** [comment]
@marusoft remove the bracket on the PR title.

**Review by rovilay — APPROVED** [review]

**Pull request merged**
